-- SELECT * FROM LocaLinezationDatabase.dbo.Translations WHERE TranslationRequestId = 1;


-- SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE';


-- SELECT COLUMN_NAME, DATA_TYPE
-- FROM INFORMATION_SCHEMA.COLUMNS
-- WHERE TABLE_NAME = 'Translations';
